# Generated by Django 3.0 on 2019-12-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20191226_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=3000)),
                ('city', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=100)),
            ],
        ),
    ]
