# Generated by Django 3.0 on 2019-12-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20191226_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items_json',
            field=models.TextField(max_length=5000),
        ),
    ]
